//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCTONKHO
    {
        public System.DateTime Thang { get; set; }
        public int MaSP { get; set; }
        public int Tondau { get; set; }
        public int TonCuoi { get; set; }
        public int SLMuaVao { get; set; }
        public int SLBanRa { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
