//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_PHIEUDV
    {
        public int MaPDV { get; set; }
        public int MaLoaiDV { get; set; }
        public decimal DonGiaDuocTinh { get; set; }
        public int SoLuong { get; set; }
        public decimal ThanhTien { get; set; }
        public decimal ThanhToanTraTruoc { get; set; }
        public decimal ThanhToanConLai { get; set; }
        public System.DateTime NgayGiao { get; set; }
        public int MaTinhTrangDV { get; set; }
    
        public virtual LOAIDV LOAIDV { get; set; }
        public virtual PHIEUDV PHIEUDV { get; set; }
        public virtual TINHTRANGDV TINHTRANGDV { get; set; }
    }
}
