//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDV()
        {
            this.CHITIET_PHIEUDV = new HashSet<CHITIET_PHIEUDV>();
        }
    
        public int MaPDV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> SDT { get; set; }
        public decimal TongTien { get; set; }
        public decimal TongTienTraTruoc { get; set; }
        public decimal TongTienConLai { get; set; }
        public int MaTinhTrangPDV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUDV> CHITIET_PHIEUDV { get; set; }
        public virtual TINHTRANGPDV TINHTRANGPDV { get; set; }
    }
}
