//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBANHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUBANHANG()
        {
            this.CT_PHIEUBANHANG = new HashSet<CT_PHIEUBANHANG>();
        }
    
        public int MaPBH { get; set; }
        public string TenKH { get; set; }
        public System.DateTime NgayLap { get; set; }
        public decimal TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUBANHANG> CT_PHIEUBANHANG { get; set; }

        
    }
}
